apiVersion: v1
kind: Service
metadata:
  name: um-service
spec:
  selector:
    type: um-node
  type: NodePort 
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    nodePort: 32700
---
apiVersion: v1 
kind: Pod
metadata:
  name: pm01
  labels:
    network: easy
    name: pm01
    type: pm-node
spec:
  hostname: pm01
  subdomain: easy
  containers:
      - name: mdb-cs-ubuntu-1604
        image: wonkywumpus/mdb-cs-ubuntu-1604:0.10
        ports:
        - containerPort: 22
        volumeMounts:
        - name: easy-keys
          mountPath: /root/.secret-easy-keys
          readOnly: true
  volumes:
      - name: easy-keys
        secret:
          secretName: easy-keys

---
apiVersion: v1 
kind: Pod
metadata:
  name: pm02
  labels:
    network: easy
    name: pm02
    type: pm-node
spec:
  hostname: pm02
  subdomain: easy
  containers:
      - name: mdb-cs-ubuntu-1604
        image: wonkywumpus/mdb-cs-ubuntu-1604:0.10
        ports:
        - containerPort: 22
        volumeMounts:
        - name: easy-keys
          mountPath: /root/.secret-easy-keys
          readOnly: true
  volumes:
      - name: easy-keys
        secret:
          secretName: easy-keys

---
apiVersion: v1 
kind: Pod
metadata:
  name: um01
  labels:
    network: easy
    name: um01
    type: um-node
spec:
  hostname: um01
  subdomain: easy
  containers:
      - name: mdb-cs-ubuntu-1604
        image: wonkywumpus/mdb-cs-ubuntu-1604:0.10
        ports:
        - containerPort: 22
        volumeMounts:
        - name: easy-keys
          mountPath: /root/.secret-easy-keys
          readOnly: true
  volumes:
      - name: easy-keys
        secret:
          secretName: easy-keys

---
apiVersion: v1 
kind: Pod
metadata:
  name: um02
  labels:
    network: easy
    name: um02
    type: um-node
spec:
  hostname: um02
  subdomain: easy
  containers:
      - name: mdb-cs-ubuntu-1604
        image: wonkywumpus/mdb-cs-ubuntu-1604:0.10
        ports:
        - containerPort: 22
        volumeMounts:
        - name: easy-keys
          mountPath: /root/.secret-easy-keys
          readOnly: true
  volumes:
      - name: easy-keys
        secret:
          secretName: easy-keys

---
apiVersion: v1 
kind: Pod
metadata:
  name: client01 
  labels:
    network: easy
    name: client01
    type: client-node
spec:
  hostname: client01 
  subdomain: easy
  containers:
      - name: mdb-cs-ubuntu-1604
        image: wonkywumpus/mdb-cs-ubuntu-1604:0.10
        ports:
        - containerPort: 22
        volumeMounts:
        - name: easy-keys
          mountPath: /root/.secret-easy-keys
          readOnly: true
  volumes:
      - name: easy-keys
        secret:
          secretName: easy-keys


